version: '3.7'

services:
  fightcore-backend:
    image: fightcore-backend
    build:
      context: .
      dockerfile: FightCore.Backend/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=.\\SQLEXPRESS;Database=FightCore;Trusted_Connection=True;MultipleActiveResultSets=true;
      - IdentityServer=http://fightcore-identity

  fightcore-identity:
    image: fightcore-identity
    build:
      context: .
      dockerfile: FightCore.Identity/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=.\\SQLEXPRESS;Database=FightCore;Trusted_Connection=True;MultipleActiveResultSets=true;